/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "鱼来",
  "description": "一个普普通通的摸鱼人罢了",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "鱼来",
        "tagline": "一个普普通通的摸鱼人罢了",
        "heroImageStyle": {
          "maxWidth": "600px",
          "width": "100%",
          "display": "block",
          "margin": "9rem auto 2rem",
          "background": "#fff",
          "borderRadius": "1rem"
        },
        "bgImage": "/image/back1.jpeg",
        "bgImageStyle": {
          "height": "615px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-443e13ce",
      "path": "/",
      "lastUpdated": "2022/4/28 下午3:03:30"
    },
    {
      "title": "javascript 字符串方法汇总",
      "frontmatter": {
        "title": "javascript 字符串方法汇总",
        "date": "2022-04-27T00:00:00.000Z",
        "categories": [
          "javascript"
        ],
        "tags": [
          "javascript"
        ]
      },
      "regularPath": "/blogs/category1/2022/javascript-string-function.html",
      "relativePath": "blogs/category1/2022/javascript-string-function.md",
      "key": "v-2a0b1495",
      "path": "/blogs/category1/2022/javascript-string-function.html",
      "headers": [
        {
          "level": 2,
          "title": "string.length",
          "slug": "string-length"
        },
        {
          "level": 2,
          "title": "string.indexOf(string,strart)",
          "slug": "string-indexof-string-strart"
        },
        {
          "level": 2,
          "title": "string.lastIndexOf(string,strart)",
          "slug": "string-lastindexof-string-strart"
        },
        {
          "level": 2,
          "title": "string.search(string)",
          "slug": "string-search-string"
        },
        {
          "level": 2,
          "title": "string.slice(start,end)",
          "slug": "string-slice-start-end"
        },
        {
          "level": 2,
          "title": "string.substring(start,end)",
          "slug": "string-substring-start-end"
        },
        {
          "level": 2,
          "title": "string.substr(start,length)",
          "slug": "string-substr-start-length"
        },
        {
          "level": 2,
          "title": "string.replace(str,replaceStr)",
          "slug": "string-replace-str-replacestr"
        },
        {
          "level": 2,
          "title": "string.toUpperCase()",
          "slug": "string-touppercase"
        },
        {
          "level": 2,
          "title": "string.toLowerCase()",
          "slug": "string-tolowercase"
        },
        {
          "level": 2,
          "title": "string.concat()",
          "slug": "string-concat"
        },
        {
          "level": 2,
          "title": "string.trim()",
          "slug": "string-trim"
        },
        {
          "level": 2,
          "title": "string.charAt()",
          "slug": "string-charat"
        },
        {
          "level": 2,
          "title": "string.charCodeAt()",
          "slug": "string-charcodeat"
        },
        {
          "level": 2,
          "title": "string.split()",
          "slug": "string-split"
        }
      ],
      "lastUpdated": "2022/4/28 下午3:03:30"
    },
    {
      "title": "Time Line",
      "frontmatter": {
        "isTimeLine": true,
        "sidebar": false,
        "isComment": false,
        "publish": false
      },
      "regularPath": "/docs/timeLine/",
      "relativePath": "docs/timeLine/README.md",
      "key": "v-4bc85126",
      "path": "/docs/timeLine/",
      "headers": [
        {
          "level": 2,
          "title": "Time Line",
          "slug": "time-line"
        }
      ],
      "lastUpdated": "2022/4/28 下午3:03:30"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "javascript Tags"
      },
      "regularPath": "/tag/javascript/",
      "key": "v-07a3e910",
      "path": "/tag/javascript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "javascript Categories"
      },
      "regularPath": "/categories/javascript/",
      "key": "v-417c2884",
      "path": "/categories/javascript/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/recoluan",
        "icon": "reco-github"
      }
    ],
    "subSidebar": "auto",
    "sidebar": "auto",
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/avatar.jpeg",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "T",
    "authorAvatar ": "/avatar.jpeg",
    "startYear": "2022"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}