/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "string": {
      "key": "string",
      "scope": "tags",
      "path": "/tag/string/",
      "pageKeys": [
        "v-7c2f8856"
      ]
    },
    "array": {
      "key": "array",
      "scope": "tags",
      "path": "/tag/array/",
      "pageKeys": [
        "v-76516a6e",
        "v-2366d7b6"
      ]
    }
  },
  "categories": {
    "javascript": {
      "key": "javascript",
      "scope": "categories",
      "path": "/categories/javascript/",
      "pageKeys": [
        "v-7c2f8856",
        "v-76516a6e",
        "v-2366d7b6"
      ]
    }
  },
  "timeline": {}
}