/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "javascript": {
      "key": "javascript",
      "scope": "tags",
      "path": "/tag/javascript/",
      "pageKeys": [
        "v-2a0b1495"
      ]
    }
  },
  "categories": {
    "javascript": {
      "key": "javascript",
      "scope": "categories",
      "path": "/categories/javascript/",
      "pageKeys": [
        "v-2a0b1495"
      ]
    }
  },
  "timeline": {}
}