/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "string",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/string/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "array",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/array/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "javascript",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/javascript/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
}]